// LocalizationManager.swift - 应用内语言设置与文本查找

import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case simplifiedChinese = "zh-Hans"
    case english = "en"
    case traditionalChinese = "zh-Hant"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .simplifiedChinese: return "中文"
        case .english: return "English"
        case .traditionalChinese: return "繁體中文"
        }
    }
}

final class LocalizationManager: ObservableObject {
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: storageKey)
        }
    }

    private let storageKey = "appLanguage"

    init() {
        let savedValue = UserDefaults.standard.string(forKey: storageKey)
        language = AppLanguage(rawValue: savedValue ?? "") ?? .simplifiedChinese
    }

    func text(_ key: String) -> String {
        if let value = Self.localizedStrings[language]?[key] {
            return value
        }
        if let fallback = Self.localizedStrings[.simplifiedChinese]?[key] {
            return fallback
        }
        return key
    }

    func text(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), arguments: arguments)
    }
}

extension LocalizationManager {
    private static let localizedStrings: [AppLanguage: [String: String]] = [
        .simplifiedChinese: [
            "app.tagline": "轻量级 macOS 清理工具",
            "settings.general": "通用设置",
            "settings.language": "语言",
            "settings.autoRefreshInterval": "自动刷新间隔",
            "settings.seconds.3": "3 秒",
            "settings.seconds.5": "5 秒",
            "settings.seconds.10": "10 秒",
            "settings.seconds.30": "30 秒",
            "settings.moveToTrash": "删除时移至废纸篓",
            "settings.moveToTrash.help": "启用后，清理的文件将移至废纸篓而非永久删除",
            "settings.general.tab": "通用",
            "settings.about.tab": "关于",
            "settings.version": "版本 1.1.0",

            "nav.dashboard": "仪表盘",
            "nav.memory": "内存清理",
            "nav.disk": "磁盘清理",
            "nav.uninstaller": "应用卸载",
            "nav.dashboard.subtitle": "系统状态总览",
            "nav.memory.subtitle": "释放内存空间",
            "nav.disk.subtitle": "清理磁盘文件",
            "nav.uninstaller.subtitle": "卸载应用及残留",

            "common.cancel": "取消",
            "common.close": "关闭",
            "common.add": "添加",
            "common.choose": "选择",
            "common.files.count": "%d 个文件",
            "common.apps.count": "%d 个应用",

            "dashboard.emptyTrash.title": "清空废纸篓？",
            "dashboard.emptyTrash.confirm": "清空",
            "dashboard.emptyTrash.message": "废纸篓中的项目会被直接删除，无法通过本应用恢复。",
            "dashboard.loading": "正在获取系统信息...",
            "dashboard.loading.hint": "首次加载可能需要几秒钟",
            "dashboard.title": "系统状态",
            "dashboard.subtitle": "实时监控您的 Mac 状态",
            "dashboard.cpu": "CPU 使用率",
            "dashboard.memory": "内存使用率",
            "dashboard.disk": "磁盘使用率",
            "dashboard.diskFree": "可用磁盘空间",
            "dashboard.cleanable": "可清理空间",
            "dashboard.cleanable.description": "包括缓存文件、日志、临时文件、废纸篓和浏览器缓存等",
            "dashboard.quickActions": "快速操作",
            "dashboard.cleanMemory": "清理内存",
            "dashboard.emptyTrash": "清空废纸篓",
            "dashboard.scanDisk": "扫描磁盘",

            "memory.title": "内存清理",
            "memory.scan": "扫描内存",
            "memory.purge": "释放内存",
            "memory.scanning": "正在扫描内存...",
            "memory.purging": "正在释放内存...",
            "memory.active": "活跃",
            "memory.inactive": "非活跃",
            "memory.wired": "连线",
            "memory.compressed": "压缩",
            "memory.free": "可用",
            "memory.details": "内存详情",
            "memory.topProcesses": "占用最高的进程",
            "memory.processName": "进程名称",
            "memory.usage": "内存占用",
            "memory.result": "释放结果",
            "memory.before": "释放前可用",
            "memory.after": "释放后可用",
            "memory.freed": "共释放 %@",
            "memory.noExtraFreed": "未释放额外内存",

            "disk.confirm.title": "确认清理",
            "disk.confirm.action": "确认清理",
            "disk.confirm.message": "将清理 %d 个分类，共释放 %@。普通文件会移至废纸篓；废纸篓分类会直接清空。",
            "disk.confirm.messageFiles": "将清除 %d 个文件，共 %@",
            "disk.scan": "扫描磁盘",
            "disk.cleanSelected": "清理选中",
            "disk.excludedPaths.help": "排除列表",
            "disk.cleanableSpace": "可清理空间",
            "disk.scanning": "正在扫描...",
            "disk.scanning.category": "扫描中",
            "disk.cleaning": "正在清理...",
            "disk.scannedFiles": "已扫描 %d 个文件",
            "disk.revealInFinder": "在 Finder 中显示",
            "disk.before": "清理前可用",
            "disk.after": "清理后可用",
            "disk.freed": "释放空间",
            "disk.title": "磁盘清理",
            "disk.emptyHint": "点击「扫描磁盘」开始扫描可清理的文件",
            "disk.moreFiles": "还有 %d 个文件未显示...",
            "disk.largeFiles.help": "大文件仅供查看，请在 Finder 中手动确认后删除",
            "disk.viewOnly": "仅供查看",
            "disk.protected": "受保护",

            "category.caches": "缓存文件",
            "category.logs": "日志文件",
            "category.tempFiles": "临时文件",
            "category.trash": "废纸篓",
            "category.downloads": "下载目录",
            "category.xcodeCache": "Xcode 缓存",
            "category.browserCache": "浏览器缓存",
            "category.largeFiles": "大文件",

            "permission.title": "需要完全磁盘访问权限",
            "permission.message": "MacCleaner 需要完全磁盘访问权限才能扫描和清理系统文件。",
            "permission.step1": "点击下方按钮打开「系统设置」",
            "permission.step2": "前往「隐私与安全性」→「完全磁盘访问权限」",
            "permission.step3": "在列表中找到并启用 MacCleaner",
            "permission.step4": "重新启动 MacCleaner",
            "permission.openSettings": "打开系统设置",
            "permission.recheck": "重新检测",
            "permission.granted": "权限已授予",
            "excluded.title": "排除列表",
            "excluded.description": "以下路径将被排除在扫描和清理范围之外",
            "excluded.empty": "暂无排除路径",
            "excluded.placeholder": "输入要排除的路径...",
            "excluded.chooseFolder": "选择文件夹",

            "uninstaller.title": "应用卸载",
            "uninstaller.search": "搜索应用...",
            "uninstaller.scanning": "正在扫描应用程序...",
            "uninstaller.empty": "未找到应用程序",
            "uninstaller.uninstall": "卸载",
            "uninstaller.select": "选择应用",
            "uninstaller.deselect": "取消选择",
            "uninstaller.uninstallApp": "卸载应用",
            "uninstaller.selected": "已选择 %d 个应用",
            "uninstaller.batch": "批量卸载",
            "uninstaller.uninstallTitle": "卸载 %@",
            "uninstaller.batchTitle": "批量卸载 %d 个应用",
            "uninstaller.noResiduals": "未发现残留文件",
            "uninstaller.residualsIntro": "将删除以下残留文件：",
            "uninstaller.selectAllResiduals": "勾选所有文件",
            "uninstaller.deselectAllResiduals": "取消勾选",
            "uninstaller.confirm": "确认卸载",
            "uninstaller.confirmBatch": "确认批量卸载",
            "uninstaller.uninstallingApp": "正在卸载 %@...",
            "uninstaller.uninstalling": "正在卸载...",
            "uninstaller.versionDetail": "版本 %@ · %@",
            "uninstaller.mode.installed": "已安装应用",
            "uninstaller.mode.orphan": "卸载残留",
            "uninstaller.scanningOrphans": "正在扫描卸载残留...",
            "uninstaller.scanningPath": "当前目录：%@",
            "uninstaller.orphansEmpty": "未发现卸载残留，您的系统很干净",
            "uninstaller.scanOrphans": "扫描残留",
            "uninstaller.orphanHint": "该应用已卸载，这是残留文件",
            "uninstaller.clean": "清理",
            "uninstaller.cleaning": "正在清理…",
            "uninstaller.cleanSelected": "清理选中",
            "uninstaller.orphansSelected": "已选择 %d 个残留 · %@",
            "uninstaller.orphanCleanTitle": "清理卸载残留",
            "uninstaller.orphanCleanMessage": "将清理 %d 个残留文件，共 %@。文件将移入废纸篓。"
        ],

        .english: [
            "app.tagline": "Lightweight macOS cleaner",
            "settings.general": "General Settings",
            "settings.language": "Language",
            "settings.autoRefreshInterval": "Auto refresh interval",
            "settings.seconds.3": "3 seconds",
            "settings.seconds.5": "5 seconds",
            "settings.seconds.10": "10 seconds",
            "settings.seconds.30": "30 seconds",
            "settings.moveToTrash": "Move deleted files to Trash",
            "settings.moveToTrash.help": "When enabled, cleaned files are moved to Trash instead of permanently deleted.",
            "settings.general.tab": "General",
            "settings.about.tab": "About",
            "settings.version": "Version 1.1.0",

            "nav.dashboard": "Dashboard",
            "nav.memory": "Memory Cleaner",
            "nav.disk": "Disk Cleaner",
            "nav.uninstaller": "App Uninstaller",
            "nav.dashboard.subtitle": "System overview",
            "nav.memory.subtitle": "Free memory",
            "nav.disk.subtitle": "Clean disk files",
            "nav.uninstaller.subtitle": "Remove apps and leftovers",

            "common.cancel": "Cancel",
            "common.close": "Close",
            "common.add": "Add",
            "common.choose": "Choose",
            "common.files.count": "%d files",
            "common.apps.count": "%d apps",

            "dashboard.emptyTrash.title": "Empty Trash?",
            "dashboard.emptyTrash.confirm": "Empty",
            "dashboard.emptyTrash.message": "Items in Trash will be deleted directly and cannot be restored by this app.",
            "dashboard.loading": "Getting system information...",
            "dashboard.loading.hint": "First load may take a few seconds",
            "dashboard.title": "System Status",
            "dashboard.subtitle": "Monitor your Mac in real time",
            "dashboard.cpu": "CPU Usage",
            "dashboard.memory": "Memory Usage",
            "dashboard.disk": "Disk Usage",
            "dashboard.diskFree": "Free Disk Space",
            "dashboard.cleanable": "Cleanable Space",
            "dashboard.cleanable.description": "Includes cache files, logs, temporary files, Trash, browser caches, and more.",
            "dashboard.quickActions": "Quick Actions",
            "dashboard.cleanMemory": "Clean Memory",
            "dashboard.emptyTrash": "Empty Trash",
            "dashboard.scanDisk": "Scan Disk",

            "memory.title": "Memory Cleaner",
            "memory.scan": "Scan Memory",
            "memory.purge": "Free Memory",
            "memory.scanning": "Scanning memory...",
            "memory.purging": "Freeing memory...",
            "memory.active": "Active",
            "memory.inactive": "Inactive",
            "memory.wired": "Wired",
            "memory.compressed": "Compressed",
            "memory.free": "Free",
            "memory.details": "Memory Details",
            "memory.topProcesses": "Top Processes",
            "memory.processName": "Process Name",
            "memory.usage": "Memory",
            "memory.result": "Freeing Result",
            "memory.before": "Before",
            "memory.after": "After",
            "memory.freed": "Freed %@",
            "memory.noExtraFreed": "No extra memory freed",

            "disk.confirm.title": "Confirm Cleanup",
            "disk.confirm.action": "Clean",
            "disk.confirm.message": "Will clean %d categories, %@ total. Files will be moved to Trash; Trash category will be directly emptied.",
            "disk.confirm.messageFiles": "Will delete %d files, %@ total",
            "disk.scan": "Scan Disk",
            "disk.cleanSelected": "Clean Selected",
            "disk.excludedPaths.help": "Excluded paths",
            "disk.cleanableSpace": "Cleanable Space",
            "disk.scanning": "Scanning...",
            "disk.scanning.category": "Scanning",
            "disk.cleaning": "Cleaning...",
            "disk.scannedFiles": "%d files scanned",
            "disk.revealInFinder": "Reveal in Finder",
            "disk.before": "Free Before",
            "disk.after": "Free After",
            "disk.freed": "Freed",
            "disk.title": "Disk Cleaner",
            "disk.emptyHint": "Click Scan Disk to find cleanable files",
            "disk.moreFiles": "%d more files are not shown...",
            "disk.largeFiles.help": "Large files are view-only. Confirm manually in Finder before deleting.",
            "disk.viewOnly": "View Only",
            "disk.protected": "Protected",

            "category.caches": "Cache Files",
            "category.logs": "Log Files",
            "category.tempFiles": "Temporary Files",
            "category.trash": "Trash",
            "category.downloads": "Downloads",
            "category.xcodeCache": "Xcode Cache",
            "category.browserCache": "Browser Cache",
            "category.largeFiles": "Large Files",

            "permission.title": "Full Disk Access Required",
            "permission.message": "MacCleaner needs Full Disk Access to scan and clean system files.",
            "permission.step1": "Click the button below to open System Settings",
            "permission.step2": "Go to Privacy & Security -> Full Disk Access",
            "permission.step3": "Find and enable MacCleaner in the list",
            "permission.step4": "Restart MacCleaner",
            "permission.openSettings": "Open System Settings",
            "permission.recheck": "Check Again",
            "permission.granted": "Permission Granted",
            "excluded.title": "Excluded Paths",
            "excluded.description": "These paths will be excluded from scanning and cleanup.",
            "excluded.empty": "No excluded paths",
            "excluded.placeholder": "Enter a path to exclude...",
            "excluded.chooseFolder": "Choose Folder",

            "uninstaller.title": "App Uninstaller",
            "uninstaller.search": "Search apps...",
            "uninstaller.scanning": "Scanning applications...",
            "uninstaller.empty": "No applications found",
            "uninstaller.uninstall": "Uninstall",
            "uninstaller.select": "Select App",
            "uninstaller.deselect": "Deselect",
            "uninstaller.uninstallApp": "Uninstall App",
            "uninstaller.selected": "%d apps selected",
            "uninstaller.batch": "Batch Uninstall",
            "uninstaller.uninstallTitle": "Uninstall %@",
            "uninstaller.batchTitle": "Batch Uninstall %d Apps",
            "uninstaller.noResiduals": "No leftover files found",
            "uninstaller.residualsIntro": "The following leftover files will be deleted:",
            "uninstaller.selectAllResiduals": "Select All Files",
            "uninstaller.deselectAllResiduals": "Deselect All",
            "uninstaller.confirm": "Confirm Uninstall",
            "uninstaller.confirmBatch": "Confirm Batch Uninstall",
            "uninstaller.uninstallingApp": "Uninstalling %@...",
            "uninstaller.uninstalling": "Uninstalling...",
            "uninstaller.versionDetail": "Version %@ · %@",
            "uninstaller.mode.installed": "Installed Apps",
            "uninstaller.mode.orphan": "Leftovers",
            "uninstaller.scanningOrphans": "Scanning leftovers...",
            "uninstaller.scanningPath": "Current: %@",
            "uninstaller.orphansEmpty": "No leftovers found, your system is clean",
            "uninstaller.scanOrphans": "Scan Leftovers",
            "uninstaller.orphanHint": "App already uninstalled, this is a leftover file",
            "uninstaller.clean": "Clean",
            "uninstaller.cleaning": "Cleaning…",
            "uninstaller.cleanSelected": "Clean Selected",
            "uninstaller.orphansSelected": "%d leftovers selected · %@",
            "uninstaller.orphanCleanTitle": "Clean Leftovers",
            "uninstaller.orphanCleanMessage": "Will clean %d leftover files, %@ total. Files will be moved to Trash."
        ],

        .traditionalChinese: [
            "app.tagline": "輕量級 macOS 清理工具",
            "settings.general": "一般設定",
            "settings.language": "語言",
            "settings.autoRefreshInterval": "自動重新整理間隔",
            "settings.seconds.3": "3 秒",
            "settings.seconds.5": "5 秒",
            "settings.seconds.10": "10 秒",
            "settings.seconds.30": "30 秒",
            "settings.moveToTrash": "刪除時移至垃圾桶",
            "settings.moveToTrash.help": "啟用後，清理的檔案將移至垃圾桶而非永久刪除",
            "settings.general.tab": "一般",
            "settings.about.tab": "關於",
            "settings.version": "版本 1.1.0",

            "nav.dashboard": "儀表板",
            "nav.memory": "記憶體清理",
            "nav.disk": "磁碟清理",
            "nav.uninstaller": "應用程式解除安裝",
            "nav.dashboard.subtitle": "系統狀態總覽",
            "nav.memory.subtitle": "釋放記憶體空間",
            "nav.disk.subtitle": "清理磁碟檔案",
            "nav.uninstaller.subtitle": "解除安裝應用程式及殘留",

            "common.cancel": "取消",
            "common.close": "關閉",
            "common.add": "新增",
            "common.choose": "選擇",
            "common.files.count": "%d 個檔案",
            "common.apps.count": "%d 個應用程式",

            "dashboard.emptyTrash.title": "清空垃圾桶？",
            "dashboard.emptyTrash.confirm": "清空",
            "dashboard.emptyTrash.message": "垃圾桶中的項目會被直接刪除，無法透過本應用程式復原。",
            "dashboard.loading": "正在取得系統資訊...",
            "dashboard.loading.hint": "首次載入可能需要幾秒鐘",
            "dashboard.title": "系統狀態",
            "dashboard.subtitle": "即時監控您的 Mac 狀態",
            "dashboard.cpu": "CPU 使用率",
            "dashboard.memory": "記憶體使用率",
            "dashboard.disk": "磁碟使用率",
            "dashboard.diskFree": "可用磁碟空間",
            "dashboard.cleanable": "可清理空間",
            "dashboard.cleanable.description": "包括快取檔案、日誌、暫存檔案、垃圾桶和瀏覽器快取等",
            "dashboard.quickActions": "快速操作",
            "dashboard.cleanMemory": "清理記憶體",
            "dashboard.emptyTrash": "清空垃圾桶",
            "dashboard.scanDisk": "掃描磁碟",

            "memory.title": "記憶體清理",
            "memory.scan": "掃描記憶體",
            "memory.purge": "釋放記憶體",
            "memory.scanning": "正在掃描記憶體...",
            "memory.purging": "正在釋放記憶體...",
            "memory.active": "活躍",
            "memory.inactive": "非活躍",
            "memory.wired": "已連線",
            "memory.compressed": "壓縮",
            "memory.free": "可用",
            "memory.details": "記憶體詳情",
            "memory.topProcesses": "佔用最高的程序",
            "memory.processName": "程序名稱",
            "memory.usage": "記憶體佔用",
            "memory.result": "釋放結果",
            "memory.before": "釋放前可用",
            "memory.after": "釋放後可用",
            "memory.freed": "共釋放 %@",
            "memory.noExtraFreed": "未釋放額外記憶體",

            "disk.confirm.title": "確認清理",
            "disk.confirm.action": "確認清理",
            "disk.confirm.message": "將清理 %d 個分類，共 %@。普通檔案會移至垃圾桶；垃圾桶分類會直接清空。",
            "disk.confirm.messageFiles": "將清除 %d 個檔案，共 %@",
            "disk.scan": "掃描磁碟",
            "disk.cleanSelected": "清理選取",
            "disk.excludedPaths.help": "排除列表",
            "disk.cleanableSpace": "可清理空間",
            "disk.scanning": "正在掃描...",
            "disk.scanning.category": "掃描中",
            "disk.cleaning": "正在清理...",
            "disk.scannedFiles": "已掃描 %d 個檔案",
            "disk.revealInFinder": "在 Finder 中顯示",
            "disk.before": "清理前可用",
            "disk.after": "清理後可用",
            "disk.freed": "釋放空間",
            "disk.title": "磁碟清理",
            "disk.emptyHint": "點擊「掃描磁碟」開始掃描可清理的檔案",
            "disk.moreFiles": "還有 %d 個檔案未顯示...",
            "disk.largeFiles.help": "大檔案僅供查看，請在 Finder 中手動確認後刪除",
            "disk.viewOnly": "僅供查看",
            "disk.protected": "受保護",

            "category.caches": "快取檔案",
            "category.logs": "日誌檔案",
            "category.tempFiles": "暫存檔案",
            "category.trash": "垃圾桶",
            "category.downloads": "下載目錄",
            "category.xcodeCache": "Xcode 快取",
            "category.browserCache": "瀏覽器快取",
            "category.largeFiles": "大檔案",

            "permission.title": "需要完整磁碟存取權限",
            "permission.message": "MacCleaner 需要完整磁碟存取權限才能掃描和清理系統檔案。",
            "permission.step1": "點擊下方按鈕開啟「系統設定」",
            "permission.step2": "前往「隱私權與安全性」->「完整磁碟存取權限」",
            "permission.step3": "在列表中找到並啟用 MacCleaner",
            "permission.step4": "重新啟動 MacCleaner",
            "permission.openSettings": "開啟系統設定",
            "permission.recheck": "重新檢測",
            "permission.granted": "權限已授予",
            "excluded.title": "排除列表",
            "excluded.description": "以下路徑將被排除在掃描和清理範圍之外",
            "excluded.empty": "暫無排除路徑",
            "excluded.placeholder": "輸入要排除的路徑...",
            "excluded.chooseFolder": "選擇資料夾",

            "uninstaller.title": "應用程式解除安裝",
            "uninstaller.search": "搜尋應用程式...",
            "uninstaller.scanning": "正在掃描應用程式...",
            "uninstaller.empty": "未找到應用程式",
            "uninstaller.uninstall": "解除安裝",
            "uninstaller.select": "選擇應用程式",
            "uninstaller.deselect": "取消選擇",
            "uninstaller.uninstallApp": "解除安裝應用程式",
            "uninstaller.selected": "已選擇 %d 個應用程式",
            "uninstaller.batch": "批次解除安裝",
            "uninstaller.uninstallTitle": "解除安裝 %@",
            "uninstaller.batchTitle": "批次解除安裝 %d 個應用程式",
            "uninstaller.noResiduals": "未發現殘留檔案",
            "uninstaller.residualsIntro": "將刪除以下殘留檔案：",
            "uninstaller.selectAllResiduals": "勾選所有檔案",
            "uninstaller.deselectAllResiduals": "取消勾選",
            "uninstaller.confirm": "確認解除安裝",
            "uninstaller.confirmBatch": "確認批次解除安裝",
            "uninstaller.uninstallingApp": "正在解除安裝 %@...",
            "uninstaller.uninstalling": "正在解除安裝...",
            "uninstaller.versionDetail": "版本 %@ · %@",
            "uninstaller.mode.installed": "已安裝應用程式",
            "uninstaller.mode.orphan": "解除安裝殘留",
            "uninstaller.scanningOrphans": "正在掃描解除安裝殘留...",
            "uninstaller.orphansEmpty": "未發現解除安裝殘留，您的系統很乾淨",
            "uninstaller.scanOrphans": "掃描殘留",
            "uninstaller.orphanHint": "該應用程式已解除安裝，這是殘留檔案",
            "uninstaller.clean": "清理",
            "uninstaller.cleaning": "正在清理…",
            "uninstaller.cleanSelected": "清理選取",
            "uninstaller.orphansSelected": "已選擇 %d 個殘留 · %@",
            "uninstaller.orphanCleanTitle": "清理解除安裝殘留",
            "uninstaller.orphanCleanMessage": "將清理 %d 個殘留檔案，共 %@。檔案將移入垃圾桶。"
        ]
    ]
}
